# Generated by Django 4.2.6 on 2023-11-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0004_alter_curso_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosYCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.alumno')),
                ('Curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.curso')),
            ],
        ),
    ]
